PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

INSERT { 
GRAPH <http://industrialinference.com/contradictions/> {
    ?x rdf:type owl:AllDisjointClasses .
    ?x owl:members ?y .
    LIST[?y ?c1 ... ?cn]	
    ?z rdf:type ?ci .
    ?z rdf:type ?cj .
} } WHERE {
    ?x rdf:type owl:AllDisjointClasses .
    ?x owl:members ?y .
    LIST[?y ?c1 ... ?cn]	
    ?z rdf:type ?ci .
    ?z rdf:type ?cj .
}
