PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

INSERT
{ 
	GRAPH <http://industrialinference.com/inferred/> {
	?zzz rdf:type ?xxx .
	}
}
WHERE
{
	?aaa rdfs:range ?xxx .
	?yyy ?aaa ?zzz .
} 
