PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

INSERT
{ 
	GRAPH <http://industrialinference.com/inferred/> {
	?xxx rdfs:subPropertyOf rdfs:member .
	}
}
WHERE
{
?xxx rdf:type rdfs:ContainerMembershipProperty .
} 
