PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

INSERT
{ 
	GRAPH <http://industrialinference.com/inferred/> {
	?zzz rdf:type ?yyy .
	}
}
WHERE
{
?xxx rdfs:subClassOf ?yyy .
?zzz rdf:type ?xxx .
} 
